<a href="https://colab.research.google.com/github/bsmgkrishna/lc/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.zeros(size = (2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
float_32_tensor = torch.tensor([3.,4.,5.])
float_32_tensor.dtype

torch.float32

In [5]:
float_16_tensor = float_32_tensor.type(torch.int32)

In [6]:
float_32_tensor*float_16_tensor

tensor([ 9., 16., 25.])

In [7]:
random_tensor = torch.rand(3,4,dtype=torch.half)
random_tensor

tensor([[0.4175, 0.3501, 0.6958, 0.1069],
        [0.0957, 0.0132, 0.1812, 0.7969],
        [0.2178, 0.0596, 0.0093, 0.2354]], dtype=torch.float16)

In [23]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([[4],[3],[2],[7]])

In [17]:
#@title Basic functions
1. elementwise multiplication
2. matrix multiplication 

In [24]:
a * b

tensor([[ 4,  8, 12, 16],
        [ 3,  6,  9, 12],
        [ 2,  4,  6,  8],
        [ 7, 14, 21, 28]])

In [26]:
torch.matmul(a , b)

tensor([44])

In [28]:
one_to_twenty = torch.tensor(range(1,21))
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [29]:
one_to_twenty.argmin() #index of minimum element

tensor(0)

In [30]:
one_to_twenty.argmax() #index of maximum element

tensor(19)