<a href="https://colab.research.google.com/github/bsmgkrishna/lc/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
torch.zeros(size = (2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
float_32_tensor = torch.tensor([3.,4.,5.])
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.int32)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 16., 25.])

In [ ]:
random_tensor = torch.rand(3,4,dtype=torch.half)
random_tensor

tensor([[0.5767, 0.6406, 0.0430, 0.6919],
        [0.1479, 0.9175, 0.8496, 0.2617],
        [0.1743, 0.8306, 0.3540, 0.5161]], dtype=torch.float16)